file(MAKE_DIRECTORY "${TEST_DIR}")
# Only paths created by this test are removed; TEST_DIR is supplied by CTest.
file(REMOVE "${TEST_DIR}/session.journal")
file(WRITE "${TEST_DIR}/orders.txt" "NEW 1 SELL 101 7\nNEW 2 SELL 101 5\nNEW 3 BUY 101 10\nCANCEL 2\nNEW 4 BUY 99 2\nBOOK\n")
execute_process(COMMAND "${EXCHANGE}" run --journal "${TEST_DIR}/session.journal"
  --input "${TEST_DIR}/orders.txt" RESULT_VARIABLE status OUTPUT_VARIABLE live ERROR_VARIABLE errors)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "CLI failed: ${errors}")
endif()
if(NOT live MATCHES "\"maker\":\"1\",\"taker\":\"3\",\"price\":\"101\",\"quantity\":\"7\"")
  message(FATAL_ERROR "CLI did not execute the expected maker")
endif()
execute_process(COMMAND "${EXCHANGE}" replay "${TEST_DIR}/session.journal"
  RESULT_VARIABLE status OUTPUT_VARIABLE replay ERROR_VARIABLE errors)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Replay failed: ${errors}")
endif()
string(REGEX MATCHALL "\{\"type\":\"book\"[^\n]*" books "${live}")
list(GET books -1 expected_book)
string(FIND "${replay}" "${expected_book}" same_book)
if(same_book LESS 0)
  message(FATAL_ERROR "Live and replay books differ")
endif()
file(WRITE "${TEST_DIR}/cancel.txt" "CANCEL 4\n")
execute_process(COMMAND "${EXCHANGE}" run --journal "${TEST_DIR}/session.journal"
  --input "${TEST_DIR}/cancel.txt" RESULT_VARIABLE status OUTPUT_VARIABLE resumed ERROR_VARIABLE errors)
string(FIND "${resumed}" [=["orders":[]]=] empty_position)
if(NOT status EQUAL 0 OR NOT resumed MATCHES "\"sequence\":\"6\"" OR empty_position EQUAL -1)
  message(FATAL_ERROR "Resume did not restore and cancel the resting order: ${resumed} ${errors}")
endif()
file(WRITE "${TEST_DIR}/invalid.txt" "NEW -1 BUY 100 1\nNEW 18446744073709551616 BUY 100 1\nCANCEL 1 extra\nNEW 7 SELL 100 2\n")
execute_process(COMMAND "${EXCHANGE}" run --journal "${TEST_DIR}/session.journal"
  --input "${TEST_DIR}/invalid.txt" RESULT_VARIABLE status OUTPUT_VARIABLE parsed ERROR_VARIABLE errors)
if(NOT status EQUAL 2 OR NOT parsed MATCHES "\"sequence\":\"7\"")
  message(FATAL_ERROR "Invalid input should fail parsing without consuming a journal sequence")
endif()
